name: elemovie
description: Sobatbisnis Movie

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  google_fonts: ^2.3.1
  shared_preferences: ^2.0.13
  encrypt: ^5.0.1
  persistent_bottom_nav_bar: ^4.0.2
  fluttertoast: ^8.0.8
  dio: ^4.0.4
  connectivity: ^3.0.6
  intl: ^0.17.0
  geolocator: ^8.2.0
  weather: ^2.0.1
  awesome_dialog: ^2.1.2
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0
  photo_view: ^0.13.0
  flutter_rating_bar: ^4.0.0
  shimmer: ^2.0.0
  lottie: ^1.2.2
  image_picker: ^0.8.4+9
  url_launcher: ^6.0.20
  sqflite: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "assets/images/ic_elemovie.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/
